doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
            geometry: string
            enum: string
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
